[package]
name = "noodles-gtf"
version = "0.9.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license.workspace = true
edition.workspace = true
rust-version = "1.64.0"
description = "Gene Transfer Format (GTF) reader and writer"
homepage = "https://github.com/zaeleus/noodles"
repository = "https://github.com/zaeleus/noodles"
documentation = "https://docs.rs/noodles-gtf"

[dependencies]
noodles-core = { path = "../noodles-core", version = "0.11.0" }
