[workspace]
members = [
  "noodles",
  "noodles-bam",
  "noodles-bcf",
  "noodles-bgzf",
  "noodles-core",
  "noodles-cram",
  "noodles-csi",
  "noodles-fasta",
  "noodles-fastq",
  "noodles-gff",
  "noodles-gtf",
  "noodles-sam",
  "noodles-tabix",
  "noodles-vcf",
]
