[package]
name = "noodles-util"
version = "0.25.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license.workspace = true
edition.workspace = true
rust-version = "1.64.0"
description = "noodles support utilities"
homepage = "https://github.com/zaeleus/noodles"
repository = "https://github.com/zaeleus/noodles"
documentation = "https://docs.rs/noodles-util"

[features]
alignment = [
  "dep:noodles-bam",
  "dep:noodles-bgzf",
  "dep:noodles-core",
  "dep:noodles-cram",
  "dep:noodles-csi",
  "dep:noodles-fasta",
  "dep:noodles-sam",
]
variant = [
  "dep:noodles-bcf",
  "dep:noodles-bgzf",
  "dep:noodles-core",
  "dep:noodles-csi",
  "dep:noodles-vcf",
]

[dependencies]
flate2 = { workspace = true }
noodles-bam = { path = "../noodles-bam", version = "0.47.0", optional = true }
noodles-bcf = { path = "../noodles-bcf", version = "0.38.0", optional = true }
noodles-bgzf = { path = "../noodles-bgzf", version = "0.25.0", optional = true }
noodles-core = { path = "../noodles-core", version = "0.12.0", optional = true }
noodles-cram = { path = "../noodles-cram", version = "0.44.0", optional = true }
noodles-csi = { path = "../noodles-csi", version = "0.25.0", optional = true }
noodles-fasta = { path = "../noodles-fasta", version = "0.30.0", optional = true }
noodles-sam = { path = "../noodles-sam", version = "0.44.0", optional = true }
noodles-vcf = { path = "../noodles-vcf", version = "0.41.0", optional = true }

[package.metadata.docs.rs]
all-features = true

[[example]]
name = "util_alignment_query"
required-features = ["alignment"]

[[example]]
name = "util_alignment_rewrite"
required-features = ["alignment"]

[[example]]
name = "util_alignment_view"
required-features = ["alignment"]

[[example]]
name = "util_variant_query"
required-features = ["variant"]

[[example]]
name = "util_variant_rewrite"
required-features = ["variant"]

[[example]]
name = "util_variant_view"
required-features = ["variant"]
