[package]
name = "noodles-tabix"
version = "0.39.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Tabix (TBI) format reader and writer"
homepage = "https://github.com/zaeleus/noodles"
repository = "https://github.com/zaeleus/noodles"
documentation = "https://docs.rs/noodles-tabix"

[features]
async = ["dep:tokio", "noodles-bgzf/async"]

[dependencies]
bit-vec.workspace = true
byteorder.workspace = true
indexmap.workspace = true
noodles-bgzf = { path = "../noodles-bgzf", version = "0.29.0" }
noodles-core = { path = "../noodles-core", version = "0.14.0" }
noodles-csi = { path = "../noodles-csi", version = "0.33.0" }

tokio = { workspace = true, optional = true, features = ["fs", "io-util"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[package.metadata.docs.rs]
features = ["async"]

[[example]]
name = "tabix_list_reference_sequence_names_async"
required-features = ["async"]

[[example]]
name = "tabix_read_header_async"
required-features = ["async"]
