[package]
name = "noodles-bgzf"
version = "0.4.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2018"
description = "Blocked gzip format (BGZF) reader and writer"
homepage = "https://github.com/zaeleus/noodles"
repository = "https://github.com/zaeleus/noodles"
documentation = "https://docs.rs/noodles-bgzf"

[features]
async = ["bytes", "futures", "num_cpus", "pin-project-lite", "tokio", "tokio-util"]

[dependencies]
byteorder = "1.2.3"
flate2 = "1.0.1"

bytes = { version = "1.0.1", optional = true }
futures = { version = "0.3.15", optional = true, default-features = false, features = ["std"] }
num_cpus = { version = "1.13.0", optional = true }
pin-project-lite = { version = "0.2.6", optional = true }
tokio = { version = "1.10.0", optional = true, features = ["io-util", "rt"] }
tokio-util = { version = "0.6.7", optional = true, features = ["codec"] }

[dev-dependencies]
tokio = { version = "1.10.0", features = ["fs", "io-std", "macros", "rt-multi-thread"] }

[package.metadata.docs.rs]
features = ["async"]
